Fix React Native Compatibility
alan2207/react-query-auth pull request #25
Opened 2023-02-24 14:33 UTC by sirine-berguiga

Hi and thank you for this library

I've tried to use it on my React Native project, but the hardcoded div is a problem. 

Here's a patch to enable customizing the error, while still defaulting to what you had (no BC break)

Enjoy!

2023-02-24 19:03 UTC, alan2207 commented on src/index.tsx
> +    renderError = (status) => <div>Unhandled status: {status}</div>,
Let's change it to the following to be able to use the error value:
`renderError = (error: Error) => <>{JSON.stringify(error)}</>,`

2023-02-24 19:04 UTC, alan2207 commented on src/index.tsx
> +    renderError?: (status: string) => JSX.Element;
`renderError?: (error: Error) => JSX.Element;`

2023-02-24 19:06 UTC, alan2207 commented on src/index.tsx
> +    return renderError(status);
Here we can render the error:

To do that, we can replace the following:

```tsx
return renderError(status);
```
With the following:
```ts
if (status === 'error') {
  return renderError(error);
}

return null;
```

2023-02-24 19:08 UTC, alan2207 requested changes
Hey @sirine-berguiga , thanks a lot for the PR. I thought I had already removed the divs, but somehow missed this. Please check out the changes to make it even better.

2023-02-27 09:15 UTC, sirine-berguiga commented
Hi @alan2207 ,
I did the requested changes and i added a note to the readme file.

Feel free to update the wording as you see fit.

2023-03-02 07:22 UTC, alan2207 approved these changes

2023-03-02 07:38 UTC, alan2207 commented
@sirine-berguiga Thanks!

2023-03-02 07:38 UTC, merged